In [41]:
import pandas as pd
import numpy as np

In [42]:
dados_1sem = 'Preços semestrais - AUTOMOTIVOS_2025.01.csv'
df_1sem = pd.read_csv(dados_1sem, sep=';')
df_1sem.head(3)

C:\Users\cassio.pereira\AppData\Local\Temp\ipykernel_2660\3132973569.py:2: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Valor de Venda, 13: Unidade de Medida, 14: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1sem = pd.read_csv(dados_1sem, sep=';')

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN

In [43]:
dados_2sem = 'Preços semestrais - AUTOMOTIVOS_2025.02.csv'
df_2sem = pd.read_csv(dados_2sem, sep=';')
df_2sem.head(3)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,4431113000100,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL,01/07/2025,"6,69",NaN,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,5297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÁ,68903-640,DIESEL,01/07/2025,"6,33",NaN,R$ / litro,BRANCA
2,NE,BA,IPIRA,AUTO POSTO AUGUSTU'S LTDA,2448248000145,SITIO SAO JOSE,SN,NaN,SEDE,44600-000,DIESEL,01/07/2025,"6,9",NaN,R$ / litro,ALE

In [44]:
df_anp = pd.concat([df_1sem, df_2sem], ignore_index= True)

In [45]:
df_anp['Valor de Venda'] = df_anp['Valor de Venda'].str.replace(',', '.').astype(float)

In [46]:
df_gasolina = df_anp.loc[df_anp['Produto'] == 'GASOLINA']
df_etanol = df_anp.loc[df_anp['Produto'] == 'ETANOL']

In [47]:
df_media_est_gaso = df_gasolina.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index()

df_media_est_gaso = df_media_est_gaso.sort_values(by='Valor de Venda', ascending= False).reset_index()

df_media_est_gaso = df_media_est_gaso.drop(columns='index')
df_media_est_gaso

   Estado - Sigla  Valor de Venda
0              AC        7.671043
1              AM        7.226496
2              RR        6.947907
3              RO        6.914577
4              SE        6.547728
5              TO        6.534131
6              DF        6.442591
7              PR        6.427747
8              PA        6.401182
9              SC        6.393332
10             BA        6.390745
11             CE        6.373081
12             AL        6.331550
13             RN        6.330973
14             PE        6.330366
15             GO        6.291102
16             MT        6.260951
17             ES        6.256656
18             RS        6.222312
19             MS        6.206580
20             RJ        6.145133
21             MG        6.130570
22             MA        6.128841
23             SP        6.091283
24             PB        6.059165
25             AP        6.041904
26             PI        5.925385